module APIConstants
  # API USER TYPE
  module API_USER_TYPE
    ANONYMOUS =1
    WOM =2
    FACEBOOK =3
    TWITTER =4
    GOOGLE_PLUS =5
    OTHERS =6
  end

  # CONTENT RELARED
  module CONTENT
    MIN_TEXT_LENGTH =1
    MAX_TEXT_LENGTH =200
  end

  # CONTENT SELECTION
  module CONTENT_SELECTION
    CONTENT_COUNT_PER_REQUEST = 20 
    
    FRESSNESS_THRESHOLD_MIN = 25 
    FRESSNESS_THRESHOLD_MAX = 8*FRESSNESS_THRESHOLD_MIN
    SPREAD_EFFICIENCY_THRESHOLD = 25 
    SPREAD_EFFICIENCY_THRESHOLD_MAX = 4*SPREAD_EFFICIENCY_THRESHOLD

    BLACKLIST_SIZE = 200
    BLACKLIST_EXPIRY_TIME = 600
  end

end